# Generated by Django 5.1.3 on 2024-12-18 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0008_area_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='vacation_managers',
            field=models.ManyToManyField(related_name='vacation_managed_areas', to=settings.AUTH_USER_MODEL),
        ),
    ]
