# Generated by Django 5.0.8 on 2024-11-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_alter_goals_cedula_alter_historicalgoals_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltableinfo',
            name='days',
            field=models.IntegerField(max_length=350),
        ),
        migrations.AlterField(
            model_name='tableinfo',
            name='days',
            field=models.IntegerField(max_length=350),
        ),
    ]
