# Generated by Django 5.0.8 on 2024-11-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_alter_historicaltableinfo_days_alter_tableinfo_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltableinfo',
            name='days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tableinfo',
            name='days',
            field=models.IntegerField(),
        ),
    ]
