# Generated by Django 5.0.8 on 2024-10-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0019_alter_vacationrequest_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacationrequest',
            name='request_file',
        ),
        migrations.RemoveField(
            model_name='vacationrequest',
            name='uploaded_by',
        ),
    ]
