# Generated by Django 5.0.8 on 2024-11-01 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0008_area_manager'),
        ('vacation', '0020_remove_vacationrequest_request_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrequest',
            name='user_job_position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='vacation_requests', to='hierarchy.jobposition'),
            preserve_default=False,
        ),
    ]
