# Generated by Django 5.0.8 on 2024-11-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0021_vacationrequest_user_job_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationrequest',
            name='sat_is_working',
            field=models.BooleanField(),
        ),
    ]
