# Generated by Django 5.1.3 on 2025-05-27 15:32

from django.db import migrations


def populate_user_area(apps, schema_editor):
    VacationRequest = apps.get_model('vacation', 'VacationRequest')
    User = apps.get_model('users', 'User')
    
    # Get all vacation requests
    vacation_requests = VacationRequest.objects.all()
    
    # Update each vacation request with the current area of the user
    for request in vacation_requests:
        user = User.objects.get(id=request.user_id)
        if user.area_id:
            request.user_area_id = user.area_id
            request.save()


def reverse_populate_user_area(apps, schema_editor):
    VacationRequest = apps.get_model('vacation', 'VacationRequest')
    VacationRequest.objects.all().update(user_area=None)


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0023_set_user_job_position'),
    ]

    operations = [
        migrations.RunPython(populate_user_area, reverse_populate_user_area),
    ]
