# Generated by Django 5.1.3 on 2025-05-27 15:32

from django.db import migrations


def populate_user_area(apps, schema_editor):
    VacationRequest = apps.get_model('vacation', 'VacationRequest')
    User = apps.get_model('users', 'User')
    
    # Get all vacation requests
    vacation_requests = VacationRequest.objects.all()
    
    # Retrieve all users in a single query and create a lookup dictionary
    users = User.objects.filter(id__in=[request.user_id for request in vacation_requests])
    user_dict = {user.id: user for user in users}
    
    # Update vacation requests in memory
    for request in vacation_requests:
        user = user_dict.get(request.user_id)
        if user and user.area_id:
            request.user_area_id = user.area_id
    
    # Save all updates in a single query
    VacationRequest.objects.bulk_update(vacation_requests, ['user_area_id'])


def reverse_populate_user_area(apps, schema_editor):
    VacationRequest = apps.get_model('vacation', 'VacationRequest')
    VacationRequest.objects.all().update(user_area=None)


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0024_vacationrequest_user_area'),
    ]

    operations = [
        migrations.RunPython(populate_user_area, reverse_populate_user_area),
    ]
