# Generated by Django 5.1.3 on 2025-05-27 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0009_area_vacation_managers'),
        ('vacation', '0024_populate_user_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrequest',
            name='user_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vacation_requests', to='hierarchy.area'),
        ),
    ]
