# Generated by Django 5.1.3 on 2025-07-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0026_vacationrequest_paid_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacationrequest',
            options={'permissions': [('payroll_approval', 'Can approve payroll'), ('view_all_vacations', 'Can view all vacation requests')]},
        ),
    ]
