# Generated by Django 5.1.3 on 2025-07-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0025_populate_user_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacationrequest',
            options={'permissions': [('payroll_approval', 'Can approve payroll'), ('view_all_vacations', 'Can view all vacation requests')]},
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='paid_days',
            field=models.PositiveIntegerField(blank=True, help_text='Días a pagar en vez de tomar, opcional', null=True),
        ),
    ]
