# Generated by Django 5.1.3 on 2025-07-23 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0026_alter_vacationrequest_options_and_more'),
        ('vacation', '0026_vacationrequest_paid_days'),
    ]

    operations = [
    ]
