# Generated by Django 5.1.3 on 2025-07-23 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0027_merge_20250723_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacationrequest',
            options={'permissions': [('payroll_approval', 'Can approve payroll'), ('view_all_vacations    ', 'Can view all vacation requests')]},
        ),
    ]
