# Generated by Django 5.1.3 on 2025-07-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0028_alter_vacationrequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacationrequest',
            options={'permissions': [('payroll_approval', 'Can approve payroll'), ('view_all_vacations', 'Can view all vacation requests')]},
        ),
    ]
