# Generated by Django 5.1.3 on 2025-07-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0010_payslip_disability_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='disability_value',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
