# Generated by Django 5.1.3 on 2025-07-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0011_alter_payslip_disability_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='disability_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
