# Generated by Django 5.1.3 on 2025-08-04 16:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0012_alter_payslip_disability_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='extra_hours',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='extra_hours_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
    ]
