# Generated by Django 5.1.3 on 2025-07-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operational_risk', '0013_alter_events_accounting_date_alter_events_close_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='events',
            name='learning',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='events',
            name='plan',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='events',
            name='public_accounts_affected',
            field=models.CharField(max_length=500),
        ),
    ]
