# Generated by Django 5.1.3 on 2025-07-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operational_risk', '0014_alter_events_description_alter_events_learning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='learning',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='plan',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='public_accounts_affected',
            field=models.CharField(max_length=250),
        ),
    ]
